# Generated by Django 5.1.2 on 2024-10-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwisko', models.CharField(max_length=100)),
                ('Imie', models.CharField(max_length=100)),
                ('Miasto', models.CharField(default='Białystok', max_length=100)),
                ('Ulica', models.CharField(max_length=100)),
                ('Wiek', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('Zalecenia', models.TextField()),
                ('pacjent_klucz_obcy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dobry_doktorek.pacjent')),
            ],
        ),
    ]
